export const fonts = [
  { Orbitron: 'Orbitron, sans-serif;' },
  { Audiowide: 'Audiowide, cursive;' },
  { 'Press Start 2P': 'Press Start 2P, cursive;' },
  { Shrikhand: 'Shrikhand, cursive;' },
  { 'Black Ops One': 'Black Ops One, cursive;' },
  { Syncopate: 'Syncopate, sans-serif;' },
  { 'Share Tech Mono': 'Share Tech Mono, monospace;' },
  { Gugi: 'Gugi, cursive;' },
  { Baumans: 'Baumans, cursive;' },
  { Megrim: 'Megrim, cursive;' },
  { Sarpanch: 'Sarpanch, sans-serif;' },
  { 'Nova Mono': 'Nova Mono, monospace;' },
  { Wallpoet: 'Wallpoet, cursive;' },
  { 'Nova Square': 'Nova Square, cursive;' },
  { 'Share Tech': 'Share Tech, sans-serif;' },
  { Geo: 'Geo, sans-serif;' },
  { 'Chela One': 'Chela One, cursive;' },
  { Rationale: 'Rationale, sans-serif;' },
  { 'Mukta Malar': 'Mukta Malar, sans-serif;' },
  { 'Nova Round': 'Nova Round, cursive;' },
  { 'Baloo Tamma': 'Baloo Tamma, cursive;' },
  { 'Baloo Bhaijaan': 'Baloo Bhaijaan, cursive;' },
  { Quintessential: 'Quintessential, cursive;' },
  { 'Baloo Bhai': 'Baloo Bhai, cursive;' },
  { 'Encode Sans Expanded': 'Encode Sans Expanded, sans-serif;' },
  { Monofett: 'Monofett, cursive;' },
  { 'Geostar Fill': 'Geostar Fill, cursive;' }
]
